import { getNamespace } from '../../utils'

export default {
  REMOVE_LANGUAGE_PERSISTENCY: getNamespace('REMOVE_LANGUAGE_PERSISTENCY'),
  UPDATE_CONFIGURATION: getNamespace('UPDATE_CONFIGURATION'),
  SET_LANGUAGE: getNamespace('SET_LANGUAGE'),
  SET_TRANSLATION: getNamespace('SET_TRANSLATION'),
  SET_FORCE_TRANSLATION: getNamespace('SET_FORCE_TRANSLATION'),
  ADD_LANGUAGE: getNamespace('ADD_LANGUAGE'),
  ADD_TRANSLATION: getNamespace('ADD_TRANSLATION'),
  FILTER_LANGUAGES: getNamespace('FILTER_LANGUAGES'),
  UPDATE_TRANSLATION: getNamespace('UPDATE_TRANSLATION')
}
